name: "Build"
on:
  push:
    branches:
    - "elm-rewrite"
jobs:
  build:
    name: "Build Source"
    runs-on: "mtaylorio-runners-k8s"
    container:
      image: "images.home.mtaylor.io/elm:latest"
    steps:
    - name: "Checkout"
      uses: "actions/checkout@v4"
    - name: "Build"
      run: "elm make src/Main.elm --output=dist/index.html"
    - name: "Upload"
      uses: "actions/upload-artifact@v4"
      with:
        name: "dist"
        path: "dist"
        if-no-files-found: "error"
        retention-days: 1
        include-hidden-files: false
  docker:
    name: "Build Docker Image"
    runs-on: "mtaylorio-runners-dind"
    needs:
    - "build"
    steps:
    - name: "Set up Docker Buildx"
      uses: "docker/setup-buildx-action@v3"
    - name: "Checkout"
      uses: "actions/checkout@v4"
    - name: "Download dist"
      uses: "actions/download-artifact@v4"
      with:
        name: "dist"
        path: "dist"
    - id: "meta"
      name: "Docker Metadata"
      uses: "docker/metadata-action@v5"
      with:
        images: "images.home.mtaylor.io/mtaylor.io"
        tags: |
          elm-rewrite
    - name: "Docker Build"
      uses: "docker/build-push-action@v6"
      with:
        push: true
        context: "."
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
